### ISSUE TITLE
Decision about the artificial neural network model

### ISSUE THREAD

**Issue by Stanley008** [Stanley008/Symbolic_Computation_2019#13]
* Discussion about choosing the right artificial neural network model for chatbot v2.0 .

**Comment by Stanley008** [comment]
Hi, due to time constraints I would advice to use pre-trained model.

**Comment by Tocrak** [comment]
Yeah, I was also thinking that there is not enough time for us to experiment with the library we are not experienced with.

**Comment by einyan03** [comment]
Since it is pre-trained model, it will also be easier for us to review and apply in our chatbot v2.0 within the time period we have now.

**Comment by Stanley008** [comment]
If we have more time, we can try to run our own model with Rottweiler and Japanese Spitz as we wanted.

**Comment by Tocrak** [comment]
I found out that we could use the cat-and-dogs model to classify animal into those two groups.

**Comment by Stanley008** [comment]
That's a great idea. We can do it.

**Comment by Tocrak** [comment]
Yeah, so do you agree with the Idea to use the cat-and-dog model and then, if there is enough time to try and train our own model with the dog breeds?

**Comment by einyan03** [comment]
Yes, AGREE!

**Comment by Stanley008** [comment]
Yes, I fully agree.

**Comment by Tocrak** [comment]
ok then, who will want to create the records in data.clj for the cat and dogs features?

**Comment by Tocrak** [comment]
actually, if we will implement the dog breeds image recognition in further versions, because one of our goals is to identify dog breeds. So in order to not remake the chatbot in future I suggest to implement the dog breed recognition from text input right now.

**Comment by einyan03** [comment]
I can create the records for two dog breeds that we've chosen earlier in data.clj. I will assign myself in the issue feature as well.

**Comment by Stanley008** [comment]
I have send you links to the cloud - dog breeds pictures, just in case we use it in further development. I can help with records for the dogs also.

**Comment by Tocrak** [comment]
After i had a look at the cortex library I found out that it will not be that hard to train our own ANN on detecting japanese spitzs and rottweilers.

**Comment by Tocrak** [comment]
I will try to finish the implementation of the ANN by the end of this weekend.

**Comment by Tocrak** [comment]
The ANN model is trained on japanese spitzs and rottweilers images and will be implemented in the chatbot
