### ISSUE TITLE
Insert basic information, history regarding dog breeds

### ISSUE THREAD

**Issue by Stanley008** [Stanley008/Symbolic_Computation_2019#20]
Basic information plus history regarding dog breeds Rottweiler and Japenese Spitz will be made. 

* [x] User questions if he wants to hear more information about chosen breed.
* [x] Rottweiler info
* [x] Japanese Spitz info

**Comment by einyan03** [comment]
I will work on collecting the history and breed information of both Rottweiler and Japanese Spitiz and store them in data.clj as dictionaries.
