### ISSUE TITLE
Chatbot v2.0 testing 

### ISSUE THREAD

**Issue by Stanley008** [Stanley008/Symbolic_Computation_2019#50]
Chatbot went through thorough testing, if any bug/ issue found - report down below the discussion with the description how was the bug found, in which step of chatbot, and what error it produced(to be easy to replicate it for other members).

Chatbot was tested: 
* [x] easter egg working
* [x] user data part
* [x] dog data part
* [x] park data part
* [x] park core(find park)
* [x] dog core(find dog)
* [x] main core(proper functionality)
* [x] image recognition

**Comment by Stanley008** [comment]
Version feature - issue - when it happens. 

Feature 21 Branch - Issue chatbot crashes -  chatbot crashes after first reply. It only continues with empty space. (In Feature 20 Branch - it works fine.)

**Comment by Tocrak** [comment]
I fixed the bug and now the chatbot should be working normally

**Comment by Tocrak** [comment]
I tested the easter eggs and both of them are working well.

**Comment by Stanley008** [comment]
Everything works fine. I tested it.
