### ISSUE TITLE
Discussion about dog breeds

### ISSUE THREAD

**Issue by Stanley008** [Stanley008/Symbolic_Computation_2019#7]
* Discussion about choosing two dog breeds for the chatbot. 
 
Dog breed list: 

* [x] Rottweiler
* [ ] Maltese
* [ ] German Shepherd
* [ ] Dachshund
* [x] Japanese Spitz
* [ ] Bulldog
* [ ] Beagle 
* [ ] Shiba Inu
* [ ] Shih Tzu
* [ ] Dobermann
* [ ] Chow Chow
* [ ] Boxer
* [ ] Toy Poodle

Data collection:

* [x] @Stanley008 
* [ ] @Tocrak 
* [ ] @einyan03

**Comment by Tocrak** [comment]
Lets choose dog breeds that have nothing in common.

**Comment by einyan03** [comment]
Yes, agree. Let's pick dog breeds with completely different colors.

**Comment by Stanley008** [comment]
I agree. Let's choose completely different dogs like Rottweiler and Japanese Spitz. 
* Big vs Small 
* Black vs White

**Comment by Tocrak** [comment]
That great but I'd like there to be a Dachshund.

**Comment by einyan03** [comment]
Rottweiler is quite cute. It also has a very significant black (and a bit of brown) so it would match one of the criteria @Stanley008 mentioned above!

**Comment by Tocrak** [comment]
So then we'll stop on Rottweiler and which one would be the other breed? The completely different one?

**Comment by Stanley008** [comment]
Japanese Spitz would be mine suggestion due to the reason that it is always white and is quite smaller than Rottweiler.

**Comment by einyan03** [comment]
Agree!!! Let's go with Japanese Spitz and Rottweiler then.

**Comment by Tocrak** [comment]
Ok, now another question is - who will collect the dog data?

**Comment by Stanley008** [comment]
The dog breeds were mine suggestion. I will do it.
